version: '3'
services:
  filmes:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: filmes_ais/api
    ports:
      - '8080:8080'
    environment:
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=filmes_ais
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql